# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94088608213744f57ef801919a1695ac22d462061da179b2c3d1576ab04234b4228ca58e7472192df5b9504f80615ce7254f937ae4d11f6a7f986879854564ca

test:
  secret_key_base: 4910a6b2dda42cbcf6f0928921f43e7302f2390100b9da40013e5b8dfc8a036090d8fb372adffdf537758f3c3bd94d7713c9306fd7e709d25650e6f6053298b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
